#!/bin/bash 
export DISPLAY=:0

cd /home/pi/Desktop/InfoTerminal/src/ ; node index.js &
cd  /home/pi/Desktop/InfoTerminal/src_contentmanagement/ ; node index.js & 
firefox-esr --new-window http://localhost:8080

exit 0

